/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.ingestion.jsonc --include-runtime=false --env-interface=IngestionBindings ingestion-configuration.d.ts` (hash: 0243f93f8835f1f9abd719d8e6d0e360)
interface __BaseEnv_IngestionBindings {
	JOB_QUEUE: Queue;
	CONTROL_LIMITER: RateLimit;
	ENVIRONMENT: "staging";
	SOURCE_RETENTION_DAYS: "30";
	DERIVED_RETENTION_DAYS: "90";
	SUPABASE_URL: "https://kvujhszkrblaovnksafx.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_TBH5eXkpm9katjkvVjuH7w_puxgL5et";
	R2_ACCOUNT_ID: "531521b13c35aabe7b97954af0e2169b";
	R2_BUCKET: "conduit-ingestion-staging";
	PDF_PROCESSOR: DurableObjectNamespace /* PdfProcessor */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_IngestionBindings {}
}
interface IngestionBindings extends __BaseEnv_IngestionBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SOURCE_RETENTION_DAYS" | "DERIVED_RETENTION_DAYS" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "R2_ACCOUNT_ID" | "R2_BUCKET">> {}
}
