/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false --strict-vars=false` (hash: 495e248937c475f99361ca59cddddd24)
interface __BaseEnv_Env {
	AUDIT_RATE_LIMITER: RateLimit;
	FUNNEL_RATE_LIMITER: RateLimit;
	ENVIRONMENT: string;
	ALLOWED_ORIGINS: string;
	SUPABASE_URL: string;
	GEMINI_MODEL: string;
	DAILY_AUDIT_LIMIT: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_ORIGINS" | "SUPABASE_URL" | "GEMINI_MODEL" | "DAILY_AUDIT_LIMIT">> {}
}
