import { auditRequestSchema, leadRequestSchema, clientEventSchema, MAX_AUDIT_BODY_BYTES } from '../shared/contracts';
import { SupabaseDatabase, type Database } from './db';
import { analysePdf } from './gemini';
import { AppError, unavailable } from './errors';
import { readJson, json } from './http';
import { hash, newToken, validatePdf, checkTurnstile } from './security';

// Non-secret bindings are generated by Wrangler; secret names are declared explicitly.
export type WorkerEnv = { [K in keyof Env]: Env[K] extends string ? string : Env[K] } & {
  GEMINI_API_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  TURNSTILE_SECRET_KEY: string;
  RATE_LIMIT_SALT: string;
};
type Dependencies = { fetcher?: typeof fetch; database?: Database };

export async function handleRequest(request: Request, env: WorkerEnv, dependencies: Dependencies = {}): Promise<Response> {
  const requestId = crypto.randomUUID();
  let origin: string | undefined;
  const fetcher = dependencies.fetcher ?? fetch;
  const db = dependencies.database ?? new SupabaseDatabase(env, fetcher);
  try {
    const path = new URL(request.url).pathname;
    if (path === '/health' && request.method === 'GET') return json({ status: 'ok' }, 200);
    const incoming = request.headers.get('Origin');
    const allowed = env.ALLOWED_ORIGINS.split(',').map(v => v.trim()).filter(Boolean);
    if (!incoming || !allowed.includes(incoming)) throw new AppError(403, 'ORIGIN_NOT_ALLOWED', 'This request is not allowed.');
    origin = incoming;
    if (!['/api/audits', '/api/leads', '/api/events'].includes(path)) throw new AppError(404, 'NOT_FOUND', 'This endpoint does not exist.');
    if (request.method === 'OPTIONS') {
      if (request.headers.get('Access-Control-Request-Method') !== 'POST') throw new AppError(405, 'METHOD_NOT_ALLOWED', 'This method is not allowed.');
      const requested = (request.headers.get('Access-Control-Request-Headers') ?? '').toLowerCase().split(',').map(s => s.trim()).filter(Boolean);
      if (requested.some(h => h !== 'content-type')) throw new AppError(403, 'HEADERS_NOT_ALLOWED', 'These request headers are not allowed.');
      return new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': origin, 'Access-Control-Allow-Methods': 'POST', 'Access-Control-Allow-Headers': 'Content-Type', 'Access-Control-Max-Age': '600', Vary: 'Origin' } });
    }
    if (request.method !== 'POST') throw new AppError(405, 'METHOD_NOT_ALLOWED', 'This method is not allowed.');
    if (!env.RATE_LIMIT_SALT || env.RATE_LIMIT_SALT.length < 32) throw unavailable();
    const ip = request.headers.get('CF-Connecting-IP');
    if (!ip && env.ENVIRONMENT === 'production') throw unavailable();
    const limiter = path === '/api/audits' ? env.AUDIT_RATE_LIMITER : env.FUNNEL_RATE_LIMITER;
    if (!limiter || !(await limiter.limit({ key: await hash(`${env.RATE_LIMIT_SALT}:${ip ?? 'local'}:${path}`) })).success) {
      throw new AppError(429, 'RATE_LIMITED', 'Too many requests. Please wait a minute before trying again.');
    }
    if (path === '/api/audits') {
      const parsed = auditRequestSchema.safeParse(await readJson(request, MAX_AUDIT_BODY_BYTES));
      if (!parsed.success) throw new AppError(400, 'INVALID_REQUEST', 'Please select a PDF up to 7 MiB and complete the security check.');
      const body = parsed.data;
      validatePdf(body.pdfBase64);
      await checkTurnstile(body.turnstileToken, new URL(origin).hostname, env.TURNSTILE_SECRET_KEY, fetcher);
      const jobId = crypto.randomUUID();
      const auditToken = newToken();
      const expiresAt = new Date(Date.now() + 86400000).toISOString();
      await db.startJob(jobId, await hash(auditToken), body.sessionId);
      try {
        const audit = await analysePdf(body.pdfBase64, env, fetcher);
        await db.completeJob(jobId, audit);
        return json({ success: true, jobId, auditToken, summary: audit.summary, expiresAt }, 200, origin);
      } catch (err) {
        try { await db.failJob(jobId); } catch { console.warn(JSON.stringify({ event: 'job_status_update_failed', requestId, jobId })); }
        throw err;
      }
    }
    if (path === '/api/leads') {
      const parsed = leadRequestSchema.safeParse(await readJson(request, 8192));
      if (!parsed.success) throw new AppError(400, 'INVALID_LEAD', 'Please check all contact details and confirm we may contact you about this audit.');
      const audit = await db.captureLead(parsed.data, await hash(parsed.data.auditToken));
      return json({ success: true, audit }, 200, origin);
    }
    const parsed = clientEventSchema.safeParse(await readJson(request, 2048));
    if (!parsed.success) throw new AppError(400, 'INVALID_EVENT', 'This event is not valid.');
    await db.recordEvent(parsed.data, 'auditToken' in parsed.data ? await hash(parsed.data.auditToken) : undefined);
    return json({ success: true }, 200, origin);
  } catch (err) {
    const safe = err instanceof AppError ? err : unavailable();
    // Never log request bodies, provider messages, IPs, contacts, tokens or PDF text.
    if (safe.status >= 500) console.warn(JSON.stringify({ event: 'request_failed', requestId, code: safe.code }));
    return json({ success: false, error: { code: safe.code, message: safe.message }, requestId }, safe.status, origin);
  }
}
// Do not pass Cloudflare's ExecutionContext as the dependency-injection argument.
export default { fetch(request: Request, env: WorkerEnv): Promise<Response> { return handleRequest(request, env); } };
