import { build } from 'esbuild-wasm';
import { readFile, mkdir, copyFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { buildEnvironment } from './build-environment.mjs';
const require = createRequire(import.meta.url);
const environment = process.argv[2] ?? 'staging';
const { api, siteKey } = buildEnvironment(environment);
if (!siteKey) console.warn('No Turnstile site key: build is review-only; audit button is disabled until configured.');
await mkdir('dist/web', { recursive: true });
await mkdir('dist/worker', { recursive: true });
await build({ entryPoints: ['src/web/main.ts'], outfile: 'dist/web/app.js', bundle: true, minify: true, format: 'esm', target: 'es2022', define: { __API_BASE_URL__: JSON.stringify(api), __TURNSTILE_SITE_KEY__: JSON.stringify(siteKey) } });
await import('./build-worker.mjs');
execFileSync(process.execPath, [require.resolve('tailwindcss/lib/cli.js'), '-i', 'src/web/styles.css', '-o', 'dist/web/app.css', '--minify'], { stdio: 'inherit' });
await copyFile('web/index.html', 'dist/web/index.html');
await copyFile('logo.png', 'dist/web/logo.png');
const csp = `default-src 'self'; script-src 'self' https://challenges.cloudflare.com; style-src 'self'; img-src 'self' data:; connect-src 'self' ${api} https://challenges.cloudflare.com; frame-src https://challenges.cloudflare.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'`;
await writeFile('dist/web/_headers', `/*\n  Content-Security-Policy: ${csp}\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Cache-Control: no-cache\n`);
const pkg = JSON.parse(await readFile('package.json', 'utf8'));
await writeFile('dist/build-info.json', JSON.stringify({ version: pkg.version, environment, apiOrigin: api, turnstileConfigured: Boolean(siteKey) }, null, 2) + '\n');
console.log(`Built ${environment}: dist/web and dist/worker (no deployment)`);
